# Generated by Django 4.0.4 on 2022-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_chart2_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart2',
            name='list1',
            field=models.CharField(default=1, max_length=124),
            preserve_default=False,
        ),
    ]
